### ISSUE TITLE
acces to private infos

### ISSUE THREAD

**Issue by revolunet** [zmoazeni/gitspective#10]
Hi

Gitspective is awesome

This must have discussed many times, but is there any way to also get private data in the timeline ? Would be very useful to estimate my work hours :)

I guess with some pure javascript+oauth2 this could work... there are some existing implementations. 

what do you think ?

**Comment by zmoazeni** [comment]
@revolunet Thanks!

I'm a "no" on this one. This is a full page javascript app with no server infrastructure. I imagine there's a couple ways to implement JS-only oauth2, but I believe it's going to be tough to keep the consumer information really secret.

**Comment by revolunet** [comment]
Yes, i think this can be done in pure client-side JS. served over https in its own domain this is safe.... i'll give it a try.
Thanks anyway !

**Comment by revolunet** [comment]
just for the record : its not possible in pure client side as GitHub deny CORS access to the final acces_token API call. The good reason is that we need to send them our client_secret param which obviously shouldnt appear in the browser... so the only way woule be to use some kind of dumb relay proxy just for that call...
