### ISSUE TITLE
include watch events in the "follows" category

### ISSUE THREAD

**Issue by michaelficarra** [zmoazeni/gitspective#4]
And possibly consider renaming it.

**edit:** Oops, just noticed the "TODO" section of the README. Sorry. At least there's an explicit issue for it now.

**Comment by zmoazeni** [comment]
No worries. Thanks for starting to file issues. The codebase is still rough so I'm certainly missing some pieces.

**Comment by zmoazeni** [comment]
Shipped as of 290ab7b43c3b491cacabbc726eaa9271f44e6e02
