### ISSUE TITLE
Only show the subject line of commits

### ISSUE THREAD

**Issue by tddyco** [zmoazeni/gitspective#6]
Proper commit messages include a subject and then optionally a more detailed message, separated by a blank line. For example:

```
Tweak the navigation

 - Remove stupid stuff.
 - Make it awesome.
```

gitspective should only display the subject, to prevent a 10 line commit link. This should also still work fine in almost every case, even messages that don't follow the standard—since they're usually just a single line.

Should be quite trivial.. I'd submit a pull request, but unfortunately I don't know CoffeeScript ;)

**Comment by zmoazeni** [comment]
All set and deployed in 95be31168c63d72e80a4752e0a608719103d0c0f
